export const SET_JOBS_OFFERS = 'SET_JOBS_OFFERS'
export const SET_OFFER = 'SET_OFFER'
export const SHOW_JOBS = 'SHOW_JOBS'
export const SHOW_JOB = 'SHOW_JOB'
export const SET_FILTER = 'SET_FILTER'
export const SET_ERROR = 'SET_ERROR'
